### PR TITLE
BOSS-30433 Update variable in string to php8

### PR DESCRIPTION
**Pull request by j-lukowicz-contorion**
Added php8.2 compatibility

### CODE REVIEW

**Review by ck86 — APPROVED** [review]
Will that work below PHP 8.2?

**Comment by j-lukowicz-contorion** [comment]
Yes, it is compatible with >=7

**Review by azhurb — APPROVED** [review]
Thanks for contributing to this beautiful open-source library 💪

**Comment by ck86** [comment]
> Thanks for contributing to this beautiful open-source library 💪

Well... we don't really contribute as we don't provide our changes to the origin.

**Comment by azhurb** [comment]
> > Thanks for contributing to this beautiful open-source library 💪
> 
> Well... we don't really contribute as we don't provide our changes to the origin.

I apologize, that was a bad joke 🫠

**Pull request merged**
